//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP.CSharp.Excercise4.AnonymousTypesAndLambdas.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDP.CSharp.Excercise4.AnonymousTypesAndLambdas.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clare Benjamin|Seychelles|21/04/2016|Vivamus Inc.
        ///Denise Wilkins|Malawi|25/04/2016|Fusce Aliquet Magna Institute
        ///Breanna Erickson|Guadeloupe|23/04/2016|Malesuada Vel LLP
        ///Cain Wilkins|Lithuania|22/04/2016|Est Nunc Incorporated
        ///Hillary Rogers|Kazakhstan|22/04/2016|Natoque Corp.
        ///Heather Burgess|Greece|26/04/2016|Consectetuer Adipiscing Inc.
        ///Kelsey Blair|Malaysia|20/04/2016|Mi Eleifend Inc.
        ///Fleur Lane|Slovenia|26/04/2016|Et Ltd
        ///Jasper Buchanan|Singapore|26/04/2016|In LLP
        ///Carson Mcdaniel|South Sudan|24/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SomePeople {
            get {
                return ResourceManager.GetString("SomePeople", resourceCulture);
            }
        }
    }
}
